document.addEventListener("DOMContentLoaded", () => {
  const KEY="orders"; if(!Storage.exists(KEY))Storage.save(KEY,[]); lucide.createIcons();
  const tbody=document.getElementById("order-list"),search=document.getElementById("order-search"),filter=document.getElementById("order-status"),dialog=document.getElementById("order-dialog"),form=document.getElementById("order-form"); let currentPage=1,editingId=null,viewing=false;
  const esc=(v)=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML},money=(v)=>new Intl.NumberFormat("es-CR",{style:"currency",currency:"USD"}).format(v),customers=()=>Storage.get("customers"),products=()=>Storage.get("products"),suppliers=()=>Storage.get("suppliers");
  function detail(o){return o.items.map((i)=>({...i,product:products().find((p)=>String(p.id)===String(i.productId))||{name:"Producto eliminado",price:i.unitPrice||0,supplierId:i.supplierId}}))}
  function render(){const term=search.value.trim().toLowerCase(),rows=Storage.get(KEY).filter((o)=>{const c=customers().find((x)=>String(x.id)===String(o.customerId));return(!term||[o.id,c?.name].join(" ").toLowerCase().includes(term))&&(filter.value==="all"||o.status===filter.value)}),result=AppCore.page(rows,currentPage);currentPage=result.current;tbody.innerHTML=result.items.map((o)=>{const c=customers().find((x)=>String(x.id)===String(o.customerId)),items=detail(o),qty=items.reduce((n,x)=>n+Number(x.quantity),0),total=items.reduce((n,x)=>n+Number(x.quantity)*Number(x.product.price),0),names=[...new Set(items.map((x)=>suppliers().find((s)=>String(s.id)===String(x.product.supplierId))?.companyName||"Sin proveedor"))];return `<tr data-id="${esc(o.id)}"><td>#${esc(String(o.id).slice(-6))}</td><td>${esc(c?.name||"Cliente eliminado")}</td><td>${qty}</td><td class="supplier-list">${names.map(esc).join(", ")}</td><td><strong>${money(total)}</strong></td><td><span class="status ${o.status}">${{pending:"Pendiente",processing:"En proceso",delivered:"Entregado"}[o.status]}</span></td><td class="crud-actions"><button data-action="view">Ver</button><button data-action="edit" data-permission="edit">Modificar</button><button data-action="delete" data-permission="delete">Eliminar</button></td></tr>`}).join("");document.querySelector(".empty-state").hidden=result.totalItems!==0;document.getElementById("order-total").textContent=rows.length;AppCore.pagination(document.getElementById("order-pagination"),result,(p)=>{currentPage=p;render()});AppCore.applyPermissions(tbody)}
  function prepare(order=null,readOnly=false){editingId=order?.id||null;viewing=readOnly;const saved=new Map((order?.items||[]).map((i)=>[String(i.productId),i])),customerSelect=document.getElementById("order-customer");dialog.querySelector("h2").textContent=readOnly?"Detalle del pedido":editingId?"Modificar pedido":"Nuevo pedido";customerSelect.innerHTML='<option value="">Selecciona un cliente</option>'+customers().map((c)=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join("");customerSelect.value=order?.customerId||"";customerSelect.disabled=readOnly;document.getElementById("order-products").innerHTML=products().map((p)=>{const line=saved.get(String(p.id)),checked=!!line,exhausted=Number(p.stock)<=0&&!checked,disabled=readOnly||exhausted;return `<label class="order-product ${exhausted?"is-exhausted":""}"><input type="checkbox" data-product="${esc(p.id)}" ${checked?"checked":""} ${disabled?"disabled":""}><span>${esc(p.name)}<small>${money(p.price)} · ${exhausted?"Agotado":`Stock: ${p.stock}`}</small></span><input type="number" min="1" max="${Math.max(Number(p.stock),Number(line?.quantity||1))}" value="${line?.quantity||1}" data-quantity="${esc(p.id)}" ${readOnly||!checked?"disabled":""}><strong data-subtotal="${esc(p.id)}">${money(Number(line?.quantity||1)*Number(p.price))}</strong></label>`}).join("");form.querySelector('button[type="submit"]').hidden=readOnly;document.getElementById("cancel-order").textContent=readOnly?"Cerrar":"Cancelar";document.getElementById("order-error").textContent="";calculate()}
  function selected(){return[...document.querySelectorAll("[data-product]:checked")].map((b)=>({productId:b.dataset.product,quantity:Number(document.querySelector(`[data-quantity="${CSS.escape(b.dataset.product)}"]`).value)}))}
  function calculate(){const items=selected(),ps=products();ps.forEach((p)=>{const q=Number(document.querySelector(`[data-quantity="${CSS.escape(String(p.id))}"]`)?.value||1),s=document.querySelector(`[data-subtotal="${CSS.escape(String(p.id))}"]`);if(s)s.textContent=money(q*Number(p.price))});document.getElementById("order-quantity").textContent=items.reduce((n,x)=>n+x.quantity,0);document.getElementById("order-amount").textContent=money(items.reduce((n,x)=>n+x.quantity*Number(ps.find((p)=>String(p.id)===String(x.productId))?.price||0),0))}
  document.getElementById("active-role").textContent=AppCore.isAdmin()?"Administrador":"Operador";document.getElementById("add-order").addEventListener("click",()=>{prepare();dialog.showModal()});document.getElementById("close-order").addEventListener("click",()=>dialog.close());document.getElementById("cancel-order").addEventListener("click",()=>dialog.close());document.getElementById("order-products").addEventListener("input",(e)=>{if(!viewing&&e.target.matches("[data-product]"))document.querySelector(`[data-quantity="${CSS.escape(e.target.dataset.product)}"]`).disabled=!e.target.checked;calculate()});
  form.addEventListener("submit",(e)=>{e.preventDefault();if(viewing)return;let items=selected();const error=document.getElementById("order-error"),ps=products();if(!form.reportValidity()||!items.length){error.textContent="Selecciona un cliente y al menos un producto disponible.";return}if(items.some((x)=>x.quantity<1||x.quantity>Number(ps.find((p)=>String(p.id)===String(x.productId))?.stock||0))){error.textContent="Revisa las cantidades y el inventario disponible.";return}items=items.map((x)=>{const p=ps.find((candidate)=>String(candidate.id)===String(x.productId));return{...x,unitPrice:Number(p.price),supplierId:p.supplierId}});const data={customerId:document.getElementById("order-customer").value,items};if(editingId)Storage.update(KEY,editingId,data);else Storage.add(KEY,{...data,status:"pending"});dialog.close();render()});
  tbody.addEventListener("click",(e)=>{const b=e.target.closest("[data-action]");if(!b)return;const order=Storage.find(KEY,b.closest("tr").dataset.id);if(!order)return;if(b.dataset.action==="view"){prepare(order,true);dialog.showModal()}else if(b.dataset.action==="edit"&&AppCore.can("edit")){prepare(order);dialog.showModal()}else if(b.dataset.action==="delete"&&AppCore.can("delete")&&confirm("¿Eliminar este pedido?")){Storage.delete(KEY,order.id);render()}});search.addEventListener("input",AppCore.debounce(()=>{currentPage=1;render()}));filter.addEventListener("change",()=>{currentPage=1;render()});render();
});
