/** Utilidades compartidas de interfaz: errores, Undo, acciones y ordenamiento. */
const AppErrors=(()=>{
  function show(error,context="Operación"){const message=error instanceof Error?error.message:String(error);console.error(`[${context}]`,error);let toast=document.getElementById("app-error-toast");if(!toast){toast=document.createElement("div");toast.id="app-error-toast";toast.className="app-toast app-toast--error";toast.setAttribute("role","alert");document.body.appendChild(toast)}toast.textContent=`${context}: ${message}`;toast.classList.add("is-visible");clearTimeout(toast._timer);toast._timer=setTimeout(()=>toast.classList.remove("is-visible"),4000)}
  function guard(callback,context){return async(...args)=>{try{return await callback(...args)}catch(error){show(error,context)}}}
  return{show,guard};
})();

const UndoManager=(()=>{
  let pending=null;
  function remove({entity,id,label="Registro",onChange=()=>{}}){if(pending)pending.finalize();const records=Storage.get(entity),index=records.findIndex((item)=>String(item.id)===String(id));if(index<0)throw new Error("El registro ya no existe.");const record=records[index];Storage.delete(entity,id);onChange();let toast=document.getElementById("undo-toast");if(!toast){toast=document.createElement("div");toast.id="undo-toast";toast.className="app-toast app-toast--undo";toast.setAttribute("role","status");document.body.appendChild(toast)}toast.innerHTML=`<span>${label} eliminado.</span><button type="button">Deshacer</button>`;toast.classList.add("is-visible");const finalize=()=>{clearTimeout(timer);toast.classList.remove("is-visible");pending=null};const undo=()=>{const current=Storage.get(entity);current.splice(Math.min(index,current.length),0,record);Storage.save(entity,current);finalize();onChange()};const timer=setTimeout(finalize,6000);toast.querySelector("button").onclick=undo;pending={finalize,undo};}
  return{remove};
})();

const UIComponents=(()=>{
  function actions({view=true,edit=true,remove=true}={}){return `<div class="crud-actions">${view?'<button data-action="view">Ver</button>':""}${edit?'<button data-action="edit" data-permission="edit">Modificar</button>':""}${remove?'<button data-action="delete" data-permission="delete">Eliminar</button>':""}</div>`}
  function makeSortable(table,columns,onChange){const state={key:null,direction:"asc"};Object.entries(columns).forEach(([index,key])=>{const th=table.querySelectorAll("thead th")[Number(index)];if(!th)return;th.classList.add("sortable-column");th.tabIndex=0;th.dataset.sortKey=key;const activate=()=>{state.direction=state.key===key&&state.direction==="asc"?"desc":"asc";state.key=key;table.querySelectorAll(".sortable-column").forEach((cell)=>cell.removeAttribute("data-sort-direction"));th.dataset.sortDirection=state.direction;onChange(state)};th.addEventListener("click",activate);th.addEventListener("keydown",(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();activate()}})});return state}
  function sort(items,state,accessors={}){if(!state?.key)return[...items];const accessor=typeof accessors[state.key]==="function"?accessors[state.key]:(item)=>item[state.key];return[...items].sort((a,b)=>{const av=accessor(a),bv=accessor(b);const result=typeof av==="number"&&typeof bv==="number"?av-bv:String(av??"").localeCompare(String(bv??""),"es",{numeric:true,sensitivity:"base"});return state.direction==="desc"?-result:result})}
  function makeDomSortable(table,columns){Object.entries(columns).forEach(([index,type])=>{const th=table.querySelectorAll("thead th")[Number(index)];if(!th)return;let direction=1;th.classList.add("sortable-column");th.addEventListener("click",()=>{direction*=-1;table.querySelectorAll(".sortable-column").forEach((cell)=>cell.removeAttribute("data-sort-direction"));th.dataset.sortDirection=direction===1?"asc":"desc";const rows=[...table.tBodies[0].rows];rows.sort((a,b)=>{const av=a.cells[index]?.textContent.trim()||"",bv=b.cells[index]?.textContent.trim()||"";const result=type==="number"?(parseFloat(av.replace(/[^0-9.-]/g,""))||0)-(parseFloat(bv.replace(/[^0-9.-]/g,""))||0):av.localeCompare(bv,"es",{numeric:true,sensitivity:"base"});return result*direction});rows.forEach((row)=>table.tBodies[0].appendChild(row))})})}
  return{actions,makeSortable,makeDomSortable,sort};
})();
window.AppErrors=AppErrors;window.UndoManager=UndoManager;window.UIComponents=UIComponents;
